#!/usr/bin/python
# load matrix files and convert to AnnData
import argparse
import json
import os
import re
import anndata as ad
import pandas as pd
from datetime import datetime
from warnings import warn
from scipy.io import mmread

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert exported Seurat matrix files to AnnData h5ad."
    )
    parser.add_argument(
        "config", type=str,
        help="Path to run_config.json generated by make_config.py <run_config.json>."
    )
    parser.add_argument(
        "-o", "--outfile_dir", type=str, default=None,
        help="Override output directory for h5ad files [config outdir]."
    )
    parser.add_argument(
        "-g", "--gene-activity", nargs="+", default=None,
        help="Assay layer(s) with gene-level activity e.g. ATAC_data. Auto-detect if blank"
    )    
    args = parser.parse_args()

    with open(args.config) as f:
        cfg = json.load(f)

    infile_dir  = cfg["outdir"]
    outfile_dir = args.outfile_dir or infile_dir
    os.makedirs(outfile_dir, exist_ok=True)

    metadata = pd.read_csv(f"{infile_dir}/metadata.csv", index_col=0)
    barcodes = open(f"{infile_dir}/barcodes.txt").read().splitlines()

    # use assays from config if populated by R, else auto-detect from directory
    if cfg.get("assays"):
        assays = cfg["assays"]
        print(f"Assays from config: {assays}")
    else:
        feature_files = [
            f for f in os.listdir(infile_dir) if f.endswith("_features.txt")
        ]
        assays = [f.replace("_features.txt", "") for f in feature_files]
        print(f"Assays auto-detected: {assays}")

    adatas = {}
    for assay in assays:
        features = open(f"{infile_dir}/{assay}_features.txt").read().splitlines()

        # find all layers for this assay
        layer_files = [
            f for f in os.listdir(infile_dir)
            if f.startswith(f"{assay}_") and f.endswith(".mtx")
        ]
        layers = [re.sub(f"^{assay}_", "", f.replace(".mtx", "")) for f in layer_files]

        # use normalised as X if available, raw as layer
        primary = "data" if "data" in layers else "counts"
        X = mmread(f"{infile_dir}/{assay}_{primary}.mtx").T.tocsr()

        adata = ad.AnnData(
            X=X,
            obs=metadata,
            var=pd.DataFrame(index=features)
        )
        adata.obs_names = barcodes
        adata.layers[primary] = X

        # load remaining layers
        for layer in layers:
            if layer == primary:
                continue
            mat = mmread(f"{infile_dir}/{assay}_{layer}.mtx").T.tocsr()
            if mat.shape != (adata.n_obs, adata.n_vars):
                print(f"  Skipping {layer}: shape {mat.shape} != ({adata.n_obs}, {adata.n_vars}), storing in uns")
                adata.uns[f"{layer}_subset"] = mat
                continue
            adata.layers[layer] = mat

        adatas[assay] = adata
        print(f"{assay}: {adata.n_obs} cells x {adata.n_vars} features, "
              f"layers: {list(adata.layers.keys())}")

    # load reductions into primary assay (RNA preferred, else first)
    primary_assay = "RNA" if "RNA" in adatas else assays[0]
    for f in os.listdir(infile_dir):
        if not f.endswith(".csv") or f == "metadata.csv":
            continue
        reduction_name = f.replace(".csv", "")
        coords = pd.read_csv(f"{infile_dir}/{f}", index_col=0).values
        adatas[primary_assay].obsm[f"X_{reduction_name}"] = coords
        print(f"Loaded reduction: {reduction_name}")

    # load scvi — use config latent_file if set, else check default location
    config_scvi = cfg.get("scvi", {}).get("latent_file")
    if config_scvi and os.path.exists(config_scvi):
        scvi_files = [os.path.basename(config_scvi)]
        infile_dir = os.path.dirname(config_scvi)  # may differ from infile_dir
    else:
        scvi_files = [
            f for f in os.listdir(infile_dir)
            if f.endswith(".csv")
            and "scvi" in f.lower()
            and f != "metadata.csv"
        ]
    
    for scvi_f in scvi_files:
        key = scvi_f.replace(".csv", "")
        adatas[primary_assay].obsm[f"X_{key}"] = pd.read_csv(
            f"{infile_dir}/{scvi_f}", index_col=0
        ).values
        print(f"Loaded scvi reduction: {key}")

    # save
    for assay, adata in adatas.items():
        out = f"{outfile_dir}/{assay}.h5ad"
        adata.write_h5ad(out)
        print(f"Saved: {out}")

    if "RNA" in adatas:
        print("\nBuilding combined h5ad (RNA as primary, others in obsm)...")
        warn("Non-RNA assays without matching feature space in obsm (feature names lost!).")
        warn("For full multimodal support with feature names, use per-assay h5ad or h5mu.")

        adata_combined = adatas["RNA"].copy()

        # gene activity: CLI > config > auto-detect by feature space match
        gene_activity_keys = args.gene_activity or cfg.get("gene_activity") or []
        if not gene_activity_keys:
            print("Note: gene_activity not specified, auto-detecting by feature space match...")
            for assay, adata in adatas.items():
                if assay == "RNA":
                    continue
                for layer_name in adata.layers.keys():
                    if adata.layers[layer_name].shape[1] == adatas["RNA"].n_vars:
                        gene_activity_keys.append(f"{assay}_{layer_name}")
                        print(f"  Auto-detected gene activity layer: {assay}_{layer_name}")

        # store gene activity as proper layers (feature names preserved)
        for key in gene_activity_keys:
            parts = key.rsplit("_", 1)
            if len(parts) != 2:
                warn(f"Cannot parse assay/layer from {key}, skipping")
                continue
            assay, layer_name = parts
            if assay not in adatas or layer_name not in adatas[assay].layers:
                warn(f"{key} not found, skipping")
                continue
            mat = adatas[assay].layers[layer_name]
            if mat.shape[1] != adatas["RNA"].n_vars:
                warn(f"{key} feature mismatch, storing in obsm instead")
                adata_combined.obsm[f"X_{key}"] = mat
                continue
            adata_combined.layers[key] = mat
            print(f"  Stored {key} as layer (feature names preserved)")

        # remaining non-RNA assays to obsm
        for assay, adata in adatas.items():
            if assay == "RNA":
                continue
            for layer_name, layer_mat in adata.layers.items():
                if f"{assay}_{layer_name}" in gene_activity_keys:
                    continue
                adata_combined.obsm[f"X_{assay}_{layer_name}"] = layer_mat
                print(f"  Stored {assay}/{layer_name} as obsm (feature names not preserved)")

        out_combined = f"{outfile_dir}/combined.h5ad"
        adata_combined.write_h5ad(out_combined)
        print(f"Saved combined h5ad: {out_combined}")
    else:
        warn("No RNA assay found, skipping combined h5ad.")

    # --- muon h5mu (full multimodal, preserves feature names) ---
    try:
        import muon as mu
        print("\nBuilding h5mu (full multimodal, preserves all feature names)...")
        mdata = mu.MuData(adatas)
        out_muon = f"{outfile_dir}/combined.h5mu"
        mdata.write(out_muon)
        print(f"Saved combined h5mu: {out_muon}")
    except ImportError:
        warn("muon not installed, skipping h5mu output.")
        warn("Install with: pip install muon.")

    print(f"\nCompleted: {datetime.now()}")

if __name__ == "__main__":
    main()