name: Build docker

on:
  workflow_run:
    workflows: ["Build and Push Image"]
    branches: [main, master]
    types: [completed]
  workflow_dispatch:

jobs:
  bundle-binaries:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only run if first workflow succeeded
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: dockerc_x86-64-gnu
            suffix: linux-x64
          - os: macos-latest
            target: dockerc_aarch64
            suffix: macos-arm

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v3

      - name: Download Architecture-Specific dockerc
        run: |
          wget "https://github.com/NilsIrl/dockerc/releases/download/v0.3.2/${{ matrix.target }}" -O dockerc
          chmod +x dockerc

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile Binary
        run: |
          ./dockerc \
            -i "docker://ghcr.io/hoganlab-fish/seurat_to_anndata:latest" \
            -o "s2a-${{ matrix.suffix }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "s2a-binary-${{ matrix.suffix }}"
          path: "s2a-${{ matrix.suffix }}"